version: '3'
services:
  mysql-master:
    image: solider12/ubuntu_mysql:1.0
    container_name: mysql-master
    network_mode: "bridge"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3307:3306"
    volumes:
      - "./master/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
      - "./master/data:/var/lib/mysql"
    links:
      - mysql-slave

  mysql-slave:
    image: solider12/ubuntu_mysql:1.0
    container_name: mysql-slave
    network_mode: "bridge"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3308:3306"
    volumes:
      - "./slave/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
      - "./slave/data:/var/lib/mysql"
