FROM ubuntu:latest

MAINTAINER guorong 1002331302@qq.com

RUN apt-get update && apt-get install sudo wget gnupg -y

RUN wget -O- https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | sudo apt-key add -

RUN apt-get update && apt-get install apt-transport-https

RUN echo "deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang\r\ndeb https://dl.bintray.com/rabbitmq/debian bionic main" > /etc/apt/sources.list.d/bintray.rabbitmq.list

RUN tee /etc/apt/sources.list.d/bintray.rabbitmq.list

RUN apt-get update && apt-get install rabbitmq-server -y --fix-missing

RUN rabbitmq-plugins enable rabbitmq_management

# For RabbitMQ
EXPOSE 5672 15672

ENTRYPOINT rabbitmq-server start
