FROM ubuntu:latest

MAINTAINER guorong 1002331302@qq.com

ADD zookeeper-3.4.9.tar.gz /usr/local

RUN mv /usr/local/zookeeper-3.4.9 /usr/local/zookeeper

RUN mkdir -p /usr/local/zookeeper/data

RUN mkdir -p /usr/local/zookeeper/logs


ENV JAVA_HOME /usr/local/java8

ENV JRE_HOME ${JAVA_HOME}/jre

ENV CLASSPATH .:${JAVA_HOME}/lib:${JRE_HOME}/lib

ENV ZK_HOME /usr/local/zookeeper

ENV PATH $PATH:$JAVA_HOME/bin:$JRE_HOME/bin:$ZK_HOME/bin

RUN cp ${ZK_HOME}/conf/zoo_sample.cfg ${ZK_HOME}/conf/zoo.cfg

RUN sed -i "s#^dataDir=.*#dataDir=/usr/local/zookeeper/data#" /usr/local/zookeeper/conf/zoo.cfg

RUN sed -i "s#^dataLogDir=.*#dataLogDir=/usr/local/zookeeper/logs#" /usr/local/zookeeper/conf/zoo.cfg

RUN echo "admin.serverPort=8084" >> /usr/local/zookeeper/conf/zoo.cfg

RUN cat /usr/local/zookeeper/conf/zoo.cfg

VOLUME ["/usr/local/java8"]

VOLUME ["/usr/local/zookeeper/data"]

VOLUME ["/usr/local/zookeeper/logs"]

EXPOSE 2181

#ENTRYPOINT ["$ZK_HOME/bin/zkServer.sh","start-foreground"]

ENTRYPOINT $ZK_HOME/bin/zkServer.sh start-foreground
